@file:Suppress("AvoidDuplicateDependencies")

import com.panzer.gradle.PanzerModExtension
import java.io.File
import net.neoforged.moddevgradle.dsl.NeoForgeExtension

// panzer.mod: panzer.neoforge-mod on the NeoForge nodes ("1.21.1"),
// panzer.fabric-mod on the Fabric ones ("1.21.1-fabric").
plugins {
    id("panzer.mod")
    `maven-publish`
    idea
}

val modProps = extensions.getByType(PanzerModExtension::class.java).props

val ringBufferCap: Long = modProps.req(project, "ring_buffer.default_capacity_pow2").toLong()
val ringBufferCacheLine: Long = modProps.req(project, "ring_buffer.cache_line_bytes").toLong()
val netCompressThreshold: Long = modProps.req(project, "network.compression_threshold_bytes").toLong()
val netCompressAlgo: String = modProps.req(project, "network.compression_algo")

val mainSourceSet = sourceSets.main.get()

pluginManager.withPlugin("net.neoforged.moddev") { configure<NeoForgeExtension> {
    runs {
        all {
            val runDir = rootProject.file("versions/${modProps.currentVersion}/run")
            if (!runDir.exists()) runDir.mkdirs()

            sourceSet = mainSourceSet
            gameDirectory = runDir

            systemProperty("celeris.ringbuffer.capacity", ringBufferCap.toString())
            systemProperty("celeris.ringbuffer.cacheline", ringBufferCacheLine.toString())
            systemProperty("celeris.network.threshold", netCompressThreshold.toString())
            systemProperty("celeris.network.algo", netCompressAlgo)
        }

        register("client") {
            client()
            systemProperty("neoforge.enabledGameTestNamespaces", modProps.modId)
        }

        register("server") {
            server()
            programArgument("--nogui")
            systemProperty("neoforge.enabledGameTestNamespaces", modProps.modId)
        }
    }
} }

sourceSets.main {
    resources {
        srcDir("src/generated/resources")
    }
}

// Natives (zstd, celeris_physics), neoforge.mods.toml expansion, legal files
// and buildAndCollect come from panzer.neoforge-mod ([natives.*], [legal]).
val nativesDir = layout.buildDirectory.dir("generated/natives")

tasks {
    val generateRuntimeRequirements = register<Task>("generateRuntimeRequirements") {
        group = "build"
        description = "Emits META-INF/celeris-runtime-requirements.properties describing the " +
                "JVM flags any consumer of this jar's FFM/vector code must pass to their own runs."

        val outputFile =
            layout.buildDirectory.file("generated/celerisRuntimeRequirements/META-INF/celeris-runtime-requirements.properties")
        outputs.file(outputFile)

        val runtimeArgs = modProps.jvmModules.values
            .filter { it.addToRuntime }
            .flatMap { it.jvmRunArgs() }
            .distinct()
        inputs.property("runtimeArgs", runtimeArgs)

        doLast {
            val file = outputFile.get().asFile
            file.parentFile.mkdirs()
            file.writeText(buildString {
                appendLine("# Generated by Celeris's build -- do not edit by hand.")
                appendLine("# Consumed by panzer-build-logic's collectPropagatedJvmArgs for any")
                appendLine("# project that depends on this jar, so its own NeoForge runs get the")
                appendLine("# flags this jar's FFM/vector code needs, without declaring them by hand.")
                appendLine("jvm.args=${runtimeArgs.joinToString(" ")}")
            })
        }
    }

    processResources {
        dependsOn(generateRuntimeRequirements)
        from(generateRuntimeRequirements.map { it.outputs.files }) { into("META-INF") }
    }
}

tasks.named("processTestResources") {
    dependsOn("collectNatives")
}

/**
 * What the test JVM picks at run time and Gradle cannot see: the native kernel
 * variant (AVX2, AVX-512, NEON) and so the code paths the physics and codec tests
 * exercise. Everything else that decides a test result -- classes, natives on
 * the classpath, JVM arguments, toolchain -- is already a task input.
 * A ValueSource, so only the returned value is a configuration input (the rest
 * of /proc/cpuinfo, like clock speeds, changes on every read).
 */
abstract class HostCpu : ValueSource<String, ValueSourceParameters.None> {
    override fun obtain(): String {
        val wanted = setOf("avx2", "avx512f", "fma", "bmi2", "asimd", "sve")
        val cpuinfo = File("/proc/cpuinfo")
        val flags = if (cpuinfo.isFile) {
            cpuinfo.useLines { lines: Sequence<String> ->
                lines.firstOrNull { it.startsWith("flags") || it.startsWith("Features") }
                    ?.substringAfter(':')?.trim()?.split(' ')?.filter { it in wanted }?.sorted()?.joinToString(",")
            } ?: ""
        } else {
            ""
        }
        return "${System.getProperty("os.name")}/${System.getProperty("os.arch")} $flags"
    }
}

val hostCpu = providers.of(HostCpu::class.java) {}

tasks.withType<Test>().configureEach {
    dependsOn("processResources")
    inputs.property("hostCpu", hostCpu)
}

// Throughput comparisons (@Tag("benchmark")) are not unit tests: they take
// seconds, assert nothing and depend on the machine. `./gradlew benchmarkTest`
// runs them on its own, every time.
tasks.named<Test>("test") {
    useJUnitPlatform {
        excludeTags("benchmark")
    }
}

tasks.register<Test>("benchmarkTest") {
    group = "verification"
    description = "Runs the @Tag(\"benchmark\") throughput comparisons (not part of check/build)."
    testClassesDirs = sourceSets.test.get().output.classesDirs
    classpath = sourceSets.test.get().runtimeClasspath
    useJUnitPlatform {
        includeTags("benchmark")
    }
    // A measurement, not a result to reuse.
    outputs.upToDateWhen { false }
    outputs.cacheIf { false }
}

idea {
    module {
        testSources.from(rootProject.file("src/test/java"))
    }
}

sourceSets {
    test {
        resources.srcDir(nativesDir)
        val generatedTestDir = project.layout.buildDirectory.dir("generated/stonecutter/test/java").get().asFile
        java.setSrcDirs(listOf(generatedTestDir))
    }
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
            // C header of the physics kernel, for native code linking against
            // the same ABI (classifier: native-headers).
            artifact(rootProject.tasks.named("nativeHeadersCelerisPhysics"))
            groupId = modProps.modGroup
            artifactId = "celeris-${modProps.currentVersion}"
            version = modProps.modVersion
        }
    }
    repositories {
        mavenLocal()
        // Static Maven tree that CI pushes to gh-pages/maven on v* tags, served at
        // https://panzerdevorg.github.io/Celeris/maven. Root build dir, so every
        // Stonecutter version publishes into the same tree.
        maven {
            name = "GitHubPages"
            url = uri(rootProject.layout.buildDirectory.dir("publish-repo"))
        }
    }
}
