{
  "formatVersion": "1.1",
  "component": {
    "group": "com.panzer.mods",
    "module": "celeris-1.21.10",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "celeris-1.21.10-0.2.1.jar",
          "url": "celeris-1.21.10-0.2.1.jar",
          "size": 3703291,
          "sha512": "28d632b5809fd4db4f01a55ab7990ef8c7f8ad668fb6870ae7240e6e2ba317a9f0176ff54b2621c078f201d8cafb95c05ca30f1e0be692670de403acec20bd27",
          "sha256": "34641c17c0d4c1219f1070d5ce4a48e3acdcd7331d04f4446767be2a31d1a3a3",
          "sha1": "4f2cd8bb05385830d1920bee7e6516ce3083e03a",
          "md5": "30786e3024843f5548b1876d357f8277"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "celeris-1.21.10-0.2.1.jar",
          "url": "celeris-1.21.10-0.2.1.jar",
          "size": 3703291,
          "sha512": "28d632b5809fd4db4f01a55ab7990ef8c7f8ad668fb6870ae7240e6e2ba317a9f0176ff54b2621c078f201d8cafb95c05ca30f1e0be692670de403acec20bd27",
          "sha256": "34641c17c0d4c1219f1070d5ce4a48e3acdcd7331d04f4446767be2a31d1a3a3",
          "sha1": "4f2cd8bb05385830d1920bee7e6516ce3083e03a",
          "md5": "30786e3024843f5548b1876d357f8277"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "celeris-1.21.10-0.2.1-sources.jar",
          "url": "celeris-1.21.10-0.2.1-sources.jar",
          "size": 3650124,
          "sha512": "54bc51222fcc8c618832582420257135cdc84b79a2e6a9fd3fd28646e106e4f81bb37559cc41853ffb54987be27d693b56391e520239a5a6c2cee695cf1140f3",
          "sha256": "4795b07adde24920f0bc58572062c55038474a3166445d675cd3dc1ae57b0f87",
          "sha1": "589a551681dff96d5699c0d2c456c7680b7049b9",
          "md5": "b0f2a88ebe50b3d36bd249e14e4df722"
        }
      ]
    }
  ]
}
