{
  "formatVersion": "1.1",
  "component": {
    "group": "com.panzer.mods",
    "module": "celeris-1.21.11",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "celeris-1.21.11-0.1.0.jar",
          "url": "celeris-1.21.11-0.1.0.jar",
          "size": 3558767,
          "sha512": "6f4e2f4f88a440f861400f893c85a30faea4da365d3c2b0c6ebdab67728ae05d499b2bb307c0613463f1e2d06afd18bc1df709cf12de550506317de231b05009",
          "sha256": "3bb058d828f51328da96123061ba4e554dc3d42aeca1c02302e2b3cce5a6ffd2",
          "sha1": "665edb94bf7c94688c917f8193d779717241c80d",
          "md5": "875f86c2a69d3656e1c5593f30375824"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "celeris-1.21.11-0.1.0.jar",
          "url": "celeris-1.21.11-0.1.0.jar",
          "size": 3558767,
          "sha512": "6f4e2f4f88a440f861400f893c85a30faea4da365d3c2b0c6ebdab67728ae05d499b2bb307c0613463f1e2d06afd18bc1df709cf12de550506317de231b05009",
          "sha256": "3bb058d828f51328da96123061ba4e554dc3d42aeca1c02302e2b3cce5a6ffd2",
          "sha1": "665edb94bf7c94688c917f8193d779717241c80d",
          "md5": "875f86c2a69d3656e1c5593f30375824"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "celeris-1.21.11-0.1.0-sources.jar",
          "url": "celeris-1.21.11-0.1.0-sources.jar",
          "size": 3527984,
          "sha512": "e9a6c95cd5beff5e9ae2c9fcdad72cf281cbea6c631127fef90b141ff672c541bc0b01d2d96e5405e691f27053dc2e8d3d2422d75f18a1f04d5f36e2483128c5",
          "sha256": "dd45211f381a0e7564b61d48a160179457429a2c9cb75804a2c4a92c1f7ab7dc",
          "sha1": "cd29e846c23b5cc04b0272b21c0ce50e3f764fb2",
          "md5": "4e352cd7ef5f04e713447fee50c1fdc9"
        }
      ]
    }
  ]
}
