{
  "formatVersion": "1.1",
  "component": {
    "group": "com.panzer.mods",
    "module": "celeris-1.21.11",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "celeris-1.21.11-0.1.0.jar",
          "url": "celeris-1.21.11-0.1.0.jar",
          "size": 3558763,
          "sha512": "8c50db37e257708d425b710f18e99a0fba91f3cf9a0994e94be1a628dd45ee3e7fdbbb2609e3a38cd7fa62b189c956a4c7ca9ffd8f17ad6d2779e22b787ab6b7",
          "sha256": "4e02777d72d1f8423bd93333b3eaa02298bf4224c3155333a038dc6ed3da8279",
          "sha1": "6f06fc613ae8681ae8ca75d8e2ae04c13928e031",
          "md5": "3d6420ed5ab37ca852bb5742d7da8be0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "celeris-1.21.11-0.1.0.jar",
          "url": "celeris-1.21.11-0.1.0.jar",
          "size": 3558763,
          "sha512": "8c50db37e257708d425b710f18e99a0fba91f3cf9a0994e94be1a628dd45ee3e7fdbbb2609e3a38cd7fa62b189c956a4c7ca9ffd8f17ad6d2779e22b787ab6b7",
          "sha256": "4e02777d72d1f8423bd93333b3eaa02298bf4224c3155333a038dc6ed3da8279",
          "sha1": "6f06fc613ae8681ae8ca75d8e2ae04c13928e031",
          "md5": "3d6420ed5ab37ca852bb5742d7da8be0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "celeris-1.21.11-0.1.0-sources.jar",
          "url": "celeris-1.21.11-0.1.0-sources.jar",
          "size": 3527984,
          "sha512": "e9a6c95cd5beff5e9ae2c9fcdad72cf281cbea6c631127fef90b141ff672c541bc0b01d2d96e5405e691f27053dc2e8d3d2422d75f18a1f04d5f36e2483128c5",
          "sha256": "dd45211f381a0e7564b61d48a160179457429a2c9cb75804a2c4a92c1f7ab7dc",
          "sha1": "cd29e846c23b5cc04b0272b21c0ce50e3f764fb2",
          "md5": "4e352cd7ef5f04e713447fee50c1fdc9"
        }
      ]
    }
  ]
}
