{
  "formatVersion": "1.1",
  "component": {
    "group": "com.panzer.mods",
    "module": "celeris-26.1",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "celeris-26.1-0.1.0.jar",
          "url": "celeris-26.1-0.1.0.jar",
          "size": 3558830,
          "sha512": "0bfa571810592cfbab49549632e3b6e2784d100e81092a2a6bc94b975f9c86bae376d1749240f71f0e07a5ba41c10d9dfb12223a155b2ce064c37057460043ad",
          "sha256": "54ef9c430855c8f2a4f997499e8455f8852d4c0c7f8a8fd1806ca35c5188e26e",
          "sha1": "81b7a748667697d364432248e5571be1667e32b9",
          "md5": "ae6fb11d4632ea806c77198103b08423"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "celeris-26.1-0.1.0.jar",
          "url": "celeris-26.1-0.1.0.jar",
          "size": 3558830,
          "sha512": "0bfa571810592cfbab49549632e3b6e2784d100e81092a2a6bc94b975f9c86bae376d1749240f71f0e07a5ba41c10d9dfb12223a155b2ce064c37057460043ad",
          "sha256": "54ef9c430855c8f2a4f997499e8455f8852d4c0c7f8a8fd1806ca35c5188e26e",
          "sha1": "81b7a748667697d364432248e5571be1667e32b9",
          "md5": "ae6fb11d4632ea806c77198103b08423"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "celeris-26.1-0.1.0-sources.jar",
          "url": "celeris-26.1-0.1.0-sources.jar",
          "size": 3527981,
          "sha512": "b72bb2f8bb5c4ce34570d0d531e8c8d8af14cc3054a9c4714f43edd20eb0c5f9c2f217afebd270468b2ca2d8214e5b05847841153718210fb02a605c9d2cf6ae",
          "sha256": "47565c5b962ed6389bd12c9faa4f535711d125a8c85d798f55fa6772364a273b",
          "sha1": "2b34f3a046ac234ce649ec959972a1bf5cd4fec2",
          "md5": "b0094f6dacc098281413b51a73d783f4"
        }
      ]
    }
  ]
}
