{
  "formatVersion": "1.1",
  "component": {
    "group": "com.panzer.mods",
    "module": "celeris-1.21.1",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "celeris-1.21.1-0.2.0.jar",
          "url": "celeris-1.21.1-0.2.0.jar",
          "size": 3702846,
          "sha512": "984e6ae1c09752b3b2fa8a2d4f1c63be8ab23bbf99d4a69a65576dada9ddc258c72fab88f1e3649feb404c44f653192b5b02948473295f5bce9dd5d81a7aff0d",
          "sha256": "a0bbb122273b29625f1e0875add6af5f4a665ede9353f581e7ae35c729832d2a",
          "sha1": "4a8dabaa6d7e9f172e9b83d05b976d5a9bc1c1b5",
          "md5": "62119743a0f5bfeb575f29e56ee2af8a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "celeris-1.21.1-0.2.0.jar",
          "url": "celeris-1.21.1-0.2.0.jar",
          "size": 3702846,
          "sha512": "984e6ae1c09752b3b2fa8a2d4f1c63be8ab23bbf99d4a69a65576dada9ddc258c72fab88f1e3649feb404c44f653192b5b02948473295f5bce9dd5d81a7aff0d",
          "sha256": "a0bbb122273b29625f1e0875add6af5f4a665ede9353f581e7ae35c729832d2a",
          "sha1": "4a8dabaa6d7e9f172e9b83d05b976d5a9bc1c1b5",
          "md5": "62119743a0f5bfeb575f29e56ee2af8a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "celeris-1.21.1-0.2.0-sources.jar",
          "url": "celeris-1.21.1-0.2.0-sources.jar",
          "size": 3649614,
          "sha512": "3a7d2789f8b6596e24d527e3e70d4d5c5f5b996212643447a5974f2c00e65f0006f0e228387daf93bc7f57b2345056d11091ea2637026aaa433b14269e390a0c",
          "sha256": "cbbf05f83ec5a07c58a72fe93d1df52e615dcc2ee88d9921e0228022b1bc85d5",
          "sha1": "995de62139cc80b9bfcd50b70d44251fde185360",
          "md5": "0784b957ff60d453d3edaecf2ce562d0"
        }
      ]
    }
  ]
}
