{
  "formatVersion": "1.1",
  "component": {
    "group": "com.panzer.mods",
    "module": "celeris-1.21.1",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "celeris-1.21.1-0.1.0.jar",
          "url": "celeris-1.21.1-0.1.0.jar",
          "size": 3558788,
          "sha512": "1f60d43a8ac7a9212ce87318233811e2ae1eb92259f08c10295c06fe6710b4fc3b6575c7ae98d451076ba1ca7e20a06260e573583c868afbb7e4776be09d6327",
          "sha256": "a49458798bc76cd22111e42ffe1148ba5fc84a0a56cd3fe1d139c2c01c33b0f5",
          "sha1": "4316bb05296aebf70ee17f72765fb8fe81dc0e35",
          "md5": "35c8c6fc2264112e2b501ba356936098"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "celeris-1.21.1-0.1.0.jar",
          "url": "celeris-1.21.1-0.1.0.jar",
          "size": 3558788,
          "sha512": "1f60d43a8ac7a9212ce87318233811e2ae1eb92259f08c10295c06fe6710b4fc3b6575c7ae98d451076ba1ca7e20a06260e573583c868afbb7e4776be09d6327",
          "sha256": "a49458798bc76cd22111e42ffe1148ba5fc84a0a56cd3fe1d139c2c01c33b0f5",
          "sha1": "4316bb05296aebf70ee17f72765fb8fe81dc0e35",
          "md5": "35c8c6fc2264112e2b501ba356936098"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "celeris-1.21.1-0.1.0-sources.jar",
          "url": "celeris-1.21.1-0.1.0-sources.jar",
          "size": 3527987,
          "sha512": "75afaee09b415efcefea889d6b475814dbff271ed257e7186325acc1cf25d4818201435d82ef41d46a8748d1ee1d2cc8ebf210755a2e5d7976ac5ccf77b98e8a",
          "sha256": "770ec1e1ef254bc47e9998bbc9d6c4370b753e846d0e1d46f9588c508c7dbc75",
          "sha1": "cbe30a574106ba9df9c9b3518fa6d326824d678a",
          "md5": "00d18dafa32dedf4e2abbf82a9953e55"
        }
      ]
    }
  ]
}
